export const ClosedListingsData = [
  {
    id: 1,
    listingNo: "2683722",
    projectName: "Video Verse",
    organisation: "Systemic Altruism",
    process: "Assignment",
    designation: "job",
    date: "15 January 2025",
    createdBy: "S. Sri Vyshalini",
    createdPlatform: "telegram",
    automatedBy: "S. Sri Vyshalini",
    automatedPlatform: "telegram",
    expiryDate: "15 February 2025",
    conversionRate: "0%",
    internshalaLink: "#",
    leaderLink: "#",
    candidateLink: "#",
    assignmentLinks: "#"
  },
  {
    id: 2,
    listingNo: "2683723",
    projectName: "UI/UX Tester",
    organisation: "Systemic Altruism",
    process: "Assignment",
    designation: "job",
    date: "13 January 2025",
    createdBy: "S. Sri Vyshalini",
    createdPlatform: "telegram",
    automatedBy: "S. Sri Vyshalini",
    automatedPlatform: "telegram",
    expiryDate: "15 February 2025",
    conversionRate: "0%",
    internshalaLink: "#",
    leaderLink: "#",
    candidateLink: "#",
    assignmentLinks: "#"
  }
];