export const activeListingsData = [
  {
    id: 1,
    projectName: "AscensionStudio",
    organisation: "Systemic Altruism",
    listingNo: "2683722", 
    process: "Assignment",
    designation: "job",
    date: "15 January 2025",
    createdBy: "S. Sri Vyshalini",
    createdPlatform: "telegram",
    automatedBy: "S. Sri Vyshalini",
    automatedPlatform: "telegram",
    expiryDate: "15 February 2025",
    conversionRate: 0.0,
    internshalaLink: "#",
    leaderLink: "#",
    candidateLink: "#",
    assignmentLinks: "#",
    assignmentType: "Loom Recording"
  },
  {
    id: 2,
    projectName: "CloudNexus",
    organisation: "Systemic Altruism",
    listingNo: "2683723",
    process: "Assignment", 
    designation: "job",
    date: "13 January 2025",
    createdBy: "S. Sri Vyshalini",
    createdPlatform: "telegram",
    automatedBy: "S. Sri Vyshalini",
    automatedPlatform: "telegram",
    expiryDate: "15 February 2025",
    conversionRate: 0.0,
    internshalaLink: "#",
    leaderLink: "#",
    candidateLink: "#",
    assignmentLinks: "#",
    assignmentType: "Google Drive"
  },
  {
    id: 3,
    projectName: "TechVanguard",
    organisation: "Systemic Altruism",
    listingNo: "2683724",
    process: "Interview",
    designation: "internship",
    date: "12 January 2025",
    createdBy: "John Smith",
    createdPlatform: "web",
    automatedBy: "John Smith",
    automatedPlatform: "web",
    expiryDate: "12 February 2025",
    conversionRate: 2.5,
    internshalaLink: "#",
    leaderLink: "#",
    candidateLink: "#",
    assignmentLinks: "#",
    assignmentType: "GitHub"
  },
  {
    id: 4,
    projectName: "InnovateHub",
    organisation: "Persist Ventures",
    listingNo: "2683725",
    process: "Test",
    designation: "internship",
    date: "10 January 2025",
    createdBy: "Mary Johnson",
    createdPlatform: "mobile",
    automatedBy: "Mary Johnson", 
    automatedPlatform: "mobile",
    expiryDate: "10 February 2025",
    conversionRate: 1.8,
    internshalaLink: "#",
    leaderLink: "#",
    candidateLink: "#",
    assignmentLinks: "#",
    assignmentType: "CodeSandbox"
  },
  {
    id: 5,
    projectName: "QuantumLeap",
    organisation: "Persist Ventures",
    listingNo: "2683726",
    process: "Assignment",
    designation: "job",
    date: "8 January 2025",
    createdBy: "David Wilson",
    createdPlatform: "web",
    automatedBy: "David Wilson",
    automatedPlatform: "web", 
    expiryDate: "8 February 2025",
    conversionRate: 3.2,
    internshalaLink: "#",
    leaderLink: "#",
    candidateLink: "#",
    assignmentLinks: "#",
    assignmentType: "Google Drive"
  },
  {
    id: 6,
    projectName: "DataSphere",
    organisation: "Persist Ventures",
    listingNo: "2683727",
    process: "Interview",
    designation: "internship",
    date: "5 January 2025",
    createdBy: "Sarah Brown",
    createdPlatform: "telegram",
    automatedBy: "Sarah Brown",
    automatedPlatform: "telegram",
    expiryDate: "5 February 2025",
    conversionRate: 2.1,
    internshalaLink: "#",
    leaderLink: "#",
    candidateLink: "#",
    assignmentLinks: "#",
    assignmentType: "Loom Recording"
  }
];