export const expiredListingsData = [
    {
      organisation: "Persist Ventures",
      listingNumber: "2686013",
      projectName: "VeneersAI",
      postedDate: "17 January 2025",
      postedOver: "Startupathon Web/Internshala",
      createdBy: "S. Sri Vyshalini",
      automatedBy: "S. Sri Vyshalini",
      conversionRate: "0.0",
      assignmentsReceived: "0",
      assignmentsSent: "0",
      totalApplications: "0",
      assignmentLinks: "https://www.loom.com/share/folder/123abc",
      reviewLinks: "No Links"
    },
    {
      organisation: "Systemic Altruism",
      listingNumber: "2686014",
      projectName: "CloudSync Pro",
      postedDate: "15 January 2025", 
      postedOver: "Internshala",
      createdBy: "R. Kumar",
      automatedBy: "R. Kumar",
      conversionRate: "2.5",
      assignmentsReceived: "5",
      assignmentsSent: "3",
      totalApplications: "12",
      assignmentLinks: "https://www.loom.com/share/folder/456def",
      reviewLinks: "No Links"
    },
    {
      organisation: "Persist Ventures",
      listingNumber: "2686015", 
      projectName: "DataViz Analytics",
      postedDate: "12 January 2025",
      postedOver: "Startupathon Web",
      createdBy: "A. Singh",
      automatedBy: "A. Singh",
      conversionRate: "1.8",
      assignmentsReceived: "2",
      assignmentsSent: "1",
      totalApplications: "8",
      assignmentLinks: "https://www.loom.com/share/folder/789ghi",
      reviewLinks: "No Links"
    },
    {
      listingNumber: "2686016",
      projectName: "AI Research Lab",
      postedDate: "10 January 2025",
      postedOver: "Internshala",
      createdBy: "M. Patel - Systemic Altruism",
      automatedBy: "M. Patel",
      conversionRate: "3.2",
      assignmentsReceived: "8",
      assignmentsSent: "6",
      totalApplications: "15",
      assignmentLinks: "https://www.loom.com/share/folder/101jkl",
      reviewLinks: "No Links"
    },
    {
      listingNumber: "2686017",
      projectName: "QuantumTech",
      postedDate: "8 January 2025",
      postedOver: "Startupathon Web/Internshala",
      createdBy: "K. Shah - Persist Ventures",
      automatedBy: "K. Shah",
      conversionRate: "2.1",
      assignmentsReceived: "4",
      assignmentsSent: "3",
      totalApplications: "10",
      assignmentLinks: "https://www.loom.com/share/folder/202mno",
      reviewLinks: "No Links"
    }
];