export const automatedListingsData = [
    {
      organization: "Persist Ventures",
      listingName: "AI Software Developer",
      projectName: "VideoVerse", 
      date: "13 January 2025",
      postedOver: "Startupathon Web/Internshala",
      conversionRate: 0.0,
      assignmentsReceived: 9,
      assignmentsSent: 507,
      newApplicants: 36,
      totalApplications: 546,
      assignmentLinks: ["https://www.loom.com/...", "https://www.loom.com/..."],
      reviewLinks: "No Review Links",
      introMessage: "Hello First off, congrats if you are here! You...",
      assignmentMessage: "Congrats on being selected as a potential F...",
      day2Followup: "Success is not always about great...",
      day4Followup: "Persistence is the twin sister of e...",
      expiryDate: "13-Feb-2025",
      createdBy: "S. Sri Vyshalini",
      automatedBy: "S. Sri Vyshalini",
    },
    {
      organization: "Systemic Altruism",
      listingName: "Full Stack Developer",
      projectName: "CloudConnect",
      date: "15 January 2025",
      postedOver: "Internshala", 
      conversionRate: 2.5,
      assignmentsReceived: 15,
      assignmentsSent: 320,
      newApplicants: 42,
      totalApplications: 378,
      assignmentLinks: ["https://www.loom.com/...", "https://www.loom.com/..."],
      reviewLinks: "Review Link",
      introMessage: "Thank you for your interest in the Full Stack Developer role...",
      assignmentMessage: "Congratulations on moving forward! Here is your assignment...",
      day2Followup: "Hope you're making good progress on the assignment...",
      day4Followup: "Just a friendly reminder about the assignment deadline...",
      expiryDate: "15-Feb-2025",
      createdBy: "S. Sri Vyshalini",
      automatedBy: "S. Sri Vyshalini"
    },
    {
      organization: "Persist Ventures",
      listingName: "Mobile App Developer",
      projectName: "HealthTracker",
      date: "18 January 2025",
      postedOver: "Startupathon",
      conversionRate: 3.2,
      assignmentsReceived: 12,
      assignmentsSent: 215,
      newApplicants: 28,
      totalApplications: 255,
      assignmentLinks: ["https://www.loom.com/..."],
      reviewLinks: "https://review.link/...",
      introMessage: "Welcome to the Mobile App Developer application process...",
      assignmentMessage: "Great to see you've made it this far! Your assignment is...",
      day2Followup: "Just checking in on your assignment progress...",
      day4Followup: "The deadline is approaching, hope you're on track...",
      expiryDate: "18-Feb-2025",
      createdBy: "S. Sri Vyshalini",
      automatedBy: "S. Sri Vyshalini"
    },
    {
      organization: "Systemic Altruism",
      listingName: "Frontend Developer",
      projectName: "EcommerceUI",
      date: "20 January 2025",
      postedOver: "Internshala",
      conversionRate: 1.8,
      assignmentsReceived: 7,
      assignmentsSent: 180,
      newApplicants: 22,
      totalApplications: 209,
      assignmentLinks: ["https://www.loom.com/...", "https://www.loom.com/..."],
      reviewLinks: "No Review Links",
      introMessage: "Thanks for applying to the Frontend Developer position...",
      assignmentMessage: "You've been selected for the technical round...",
      day2Followup: "Checking in regarding the frontend assignment...",
      day4Followup: "Final reminder about the assignment submission...",
      expiryDate: "20-Feb-2025",
      createdBy: "S. Sri Vyshalini",
      automatedBy: "S. Sri Vyshalini"
    }
  ];